### ISSUE TITLE
Option to suppress `docker-entrypoint.sh` output

### ISSUE THREAD

**Issue by pianomansam** [wodby/php#10]
Some of our local environment tooling works by running `docker exec` on Drupal PHP containers and doing something with the output. The main usecase is automatically opening the like that `drush uli` outputs. 

But the output from https://github.com/wodby/php/blob/master/7.1/docker-entrypoint.sh#L18 gets in the way of this since on `wodby/drupal-php` it outputs this:

```
/docker-entrypoint.sh: running /docker-entrypoint-init.d/10-drupal-php.sh
```

I would like to propose that this line is suppressed unless the `DEBUG` environment variable is set.

**Comment by pianomansam** [comment]
Closing in favor of my pull request

**Comment by pianomansam** [comment]
Pull request to do what I'm envisioning: #11

**Comment by csandanov** [comment]
Fixed https://github.com/wodby/php/pull/11#issuecomment-334684792
