### ISSUE TITLE
Unable to start php container when using Git worktree 

### ISSUE THREAD

**Issue by zviryatko** [wodby/php#100]
When using `git worktree` php containers can't be started because it runs git command in entrypoint script. Since git worktree instead of storing everything in `.git` dir it provides `.git` file with the next content:
```
gitdir: /home/user/project/.git/worktrees/branch-name
```
so until this directory isn't accessible any git command inside the container will not work.
To solve this issue needs to share this path inside the container:
```
php:
    volumes:
      - /home/user/project/.git:/home/user/project/.git
```
I think it's better to add to documentation FAQ

**Comment by csandanov** [comment]
I didn't work with git worktree, so `git config --global` doesn't work?  is it because there's no `.git/config`?

**Comment by zviryatko** [comment]
Yes, exactly, any git command in project directory.

**Comment by csandanov** [comment]
Fixed
