### ISSUE TITLE
Do not change the owner of all files in $FILES_DIR

### ISSUE THREAD

**Issue by tamasd** [wodby/php#101]
Since https://github.com/wodby/php/commit/544532ee981d9f2e7b4b696d6e00361fca74b07b, `init_container` changes the owner of all files in `/mnt/files/local_mount`. This causes issues when external scripts (or even the IDE) try to change these files. It is not given that user `1000` will be in the `www-data` group, or even `www-data` (user or group) exists on the host machine outside of docker (e.g. dev laptop with only git, docker and an IDE; disposable Jenkins worker instance with a minimal install).

**Comment by csandanov** [comment]
You're right, this may cause unexpected issues, we should avoid `www-data` permissions unless it's explicitly required
