### ISSUE TITLE
Warning: Version warning: Imagick was compiled against ImageMagick version 1801 but version 1802 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0

### ISSUE THREAD

**Issue by net7** [wodby/php#109]
I get this error with the php image wodby/php:7.4-dev-macos.
I think you need to change the version of ImageMagick that is hardcoded and it's different from the one expected for the php library.

**Comment by csandanov** [comment]
there's only one version of imagick in the alpine repository, we hardcode version just to keep track when it's updated
