### ISSUE TITLE
caching_sha2_password.so library not found

### ISSUE THREAD

**Issue by beltofte** [wodby/php#122]
When using the Wodby PHP container and trying to connect to a MySQL 8 container / service using the mysql cli command ( mariadb-client) is it failing due to caching_sha2_password.so library not found. The full error message is:

_wodby@php.container:/var/www/html $ mysql -u php -p -h mysql
Enter password: 
ERROR 1045 (28000): Plugin caching_sha2_password could not be loaded: Error loading shared library /usr/lib/mariadb/plugin/caching_sha2_password.so: No such file or directory_

Suggestion: add the MariaDB [caching_sha2_password](https://mariadb.com/kb/en/caching_sha2_password-authentication-plugin/) to the container.

The only temporary solution I found is to switch the MySQL 8 container / service to use 'mysql_native_password' as default authentication plugin.

**Comment by csandanov** [comment]
Could you try latest image, I've added mariadb-connector-c that contains caching_sha2_password.so
