### ISSUE TITLE
Add "pdo_sqlsrv.client_buffer_max_kb_size" and "sqlsrv.ClientBufferMaxKBSize" now that sqlsrv is available

### ISSUE THREAD

**Issue by gertvdb** [wodby/php#124]
Thanks for adding the "sqlsrv" extension!  (https://github.com/wodby/php/issues/48)

Our legacy application uses "buffered" queries therefor i need to set (increase) "pdo_sqlsrv.client_buffer_max_kb_size" and "sqlsrv.ClientBufferMaxKBSize" in php.ini
https://www.php.net/manual/en/sqlsrv.configuration.php#120109

can you please add this configuration or is their another way I can add it to the php.ini?

**Comment by gertvdb** [comment]
Or should I mount a custom php-extra.ini for this ?

```
volumes:
   - "./.docker/php/php-extra.ini:/usr/local/etc/php/conf.d/php-extra.ini"
```

**Comment by csandanov** [comment]
New env vars have been added https://github.com/wodby/php/blob/master/7/templates/docker-php-ext-sqlsrv.ini.tmpl
