### ISSUE TITLE
ps: unrecognized option: p

### ISSUE THREAD

**Issue by iVegas** [wodby/php#130]
I'm using the https://github.com/resque/php-resque library on the project. So there is a worker script handling single/multiple php processes.

```
docker-compose exec php bash -c 'REDIS_BACKEND=redis:6379 QUEUE="*" COUNT=2  vendor/bin/resque'
```
So the problem is when trying to stop the process of that script then the error messages related to the BusyBox appeared (or nothing happened and looks like the process become frozen). This is the easiest scenario that can be reproduced. There also some scenarios which break the work of processing of the Drupal kernel in the script app. But it hard to reproduce and I'm not sure that I can provide many details regarding those cases.

See the log of the php container right after an attempt to stop the script:

![image](https://user-images.githubusercontent.com/11544787/101790592-4f892880-3b0b-11eb-8ff8-d1090ae83526.png)
```
[notice] Shutting down
[notice] Shutting down
ps: unrecognized option: p
ps: unrecognized option: p
BusyBox v1.31.1 () multi-call binary.

Usage: ps [-o COL1,COL2=HEADER]

Show list of processes

        -o COL1,COL2=HEADER     Select columns for display
```

After some googling I found related issues. Here is one of them https://github.com/rmohr/docker-activemq/issues/40 . Hope this will help.
Also tried to perform those scenarios using other php images (like https://hub.docker.com/r/devwithlando/php) and those issues stopped to appear.

Thanks

**Comment by csandanov** [comment]
`ps` in alpine is a part of busybox, hence implements a limited number of options, maybe installing `procps` from alpine package can help. Anyway, not wodby/php issue at all

**Comment by iVegas** [comment]
Can be somehow defined by some environment variable this package to install?

**Comment by csandanov** [comment]
no, we're not going to do that for some project that not designed to be run in docker
