### ISSUE TITLE
The version of Xdebug does not follow the compatibility with PHP version

### ISSUE THREAD

**Issue by Kwadz** [wodby/php#132]
The version of Xdebug is static while for PHP it's dynamic via the `.env` file. For example we can define `PHP_TAG=7.1` while Xdebug 3 is compatible with PHP versions >= 7.2. I tested with 7.1 and the debugging stopped working.

I think we should either include the logic of the [PHP Version Support](https://xdebug.org/docs/compat) and include the proper template _docker-php-ext-xdebug-2.ini.tmpl_ or _docker-php-ext-xdebug-3.ini.tmpl_ according to the situation. 

What do you think?

**Comment by csandanov** [comment]
7.1 has reached EOL in 2019 and we no longer support it, you can still use old tags where 7.1 existed
