### ISSUE TITLE
Missing preloadable_libiconv.so

### ISSUE THREAD

**Issue by petrozavodsky** [wodby/php#142]
File `/usr/lib/preloadable_libiconv. so` is missing from the image.

What causes problems similar to issies #25 

And also part of the example from the readme 

`
You can run Crond with this image changing the command to sudo -E LD_PRELOAD=/usr/lib/preloadable_libiconv.so crond -f -d 0 and mounting a crontab file to ./crontab:/etc/crontabs/www-data. Example crontab file contents:`

 becomes irrelevant.

**Comment by csandanov** [comment]
Thanks for reporting this, gnu-libiconv now installed from the main repo, not edge. This however doesn't resolve #25

**Comment by petrozavodsky** [comment]
@csandanov In this case, installing gnu-libiconv from main does not solve the problem
