### ISSUE TITLE
Diocument how to use PHP_EXTENSIONS_DISABLE

### ISSUE THREAD

**Issue by andypost** [wodby/php#147]
setting this environment variable in docker-compose `PHP_EXTENSIONS_DISABLE=sqlsrv rdkafka pgsql pdo_sqlsrv pdo_pgsql pcov mongodb ldap intl imap grpc event ds ast ampq` brings notice

`WARNING: instructed to disable module sqlsrv rdkafka pgsql pdo_sqlsrv pdo_pgsql pcov mongodb ldap intl imap grpc event ds ast ampq but it was not found`

**Comment by andypost** [comment]
If I use `, ` as separator it still can't find each extension

**Comment by andypost** [comment]
It works as comma separated
 `PHP_EXTENSIONS_DISABLE: 'sqlsrv,rdkafka,pgsql,pdo_sqlsrv,pdo_pgsql,pcov,mongodb,ldap,intl,imap,grpc,event,ds,ast,amqp'`

**Comment by csandanov** [comment]
it's already documented at https://github.com/wodby/php#php-extensions
