### ISSUE TITLE
PHP 8.1 incompatible extensions

### ISSUE THREAD

**Issue by csandanov** [wodby/php#159]
- ~~apcu (depecration notices https://github.com/krakjoe/apcu/issues/425)~~
- ~~ds~~
- ~~rdkafka~~
- ~~yaml~~
- ~~blackfire~~
- ~~newrelic https://github.com/newrelic/newrelic-php-agent/issues/327~~
- mcrypt

alpha/beta versions:
- ~~mongodb (alpha)~~
- ~~sqlsrv, pdo_sqlsrv (beta)~~

https://github.com/remicollet/remirepo/issues/177

**Comment by back-2-95** [comment]
Blackfire extension was released for PHP 8.1
