### ISSUE TITLE
Could you add support for FFI?

### ISSUE THREAD

**Issue by lyrixx** [wodby/php#161]
FFI seems missing from the available extensions, and it is shipped by default with PHP 7.4 but it is missing in the image.

Could you add it please?

**Comment by csandanov** [comment]
sounds like a very specific extension which is also experimental according to the [docs](https://www.php.net/manual/en/intro.ffi.php) to include it to the generic image

**Comment by lyrixx** [comment]
Actually you remove everything to add new php extension. You you can ship it, but not enable it

**Comment by lyrixx** [comment]
I don't work on the project that use your project anymore. Thus I'm closing this issue. Thanks
