### ISSUE TITLE
Controlling allow_url_fopen value 

### ISSUE THREAD

**Issue by meladawy** [wodby/php#17]
I'd like to know if there any possibility turn off allow_url_fopen in my setup. We have some security constrains in our server and we have to follow this security instructions.

**Comment by csandanov** [comment]
Env vars `PHP_ALLOW_URL_FOPEN` and `PHP_DEFAULT_SOCKET_TIMEOUT` have been added since [3.5.0](https://github.com/wodby/php/releases/tag/3.5.0)
