### ISSUE TITLE
Replace dev-macos images with multi-arch images

### ISSUE THREAD

**Issue by mxr576** [wodby/php#175]
I very far away to be an expert in [multi-arch images](https://docs.docker.com/build/building/multi-platform/) but if I understand it right than the "special" dev-macos images for MacOS users could be "merged" in the standard images and released under one time. 

If this would be possible then we can get rid of manual- or automated workarounds for using the right image versions on MacOS because Docker would automatically pull them.

Busybox is a good example for "one image"/one tagged release for multiple architectures. https://hub.docker.com/_/busybox/tags

**Comment by csandanov** [comment]
`-dev-macos` images are just images with a different default user uid/gid, multi-arch is about processor architecture, you can use `linux/arm64` not only on mac (but for example on aws graviton) and you can have mac with amd64 arch
