### ISSUE TITLE
Locales not working

### ISSUE THREAD

**Issue by manueleone** [wodby/php#177]
Hi,
first of all, thank you for your work!

I noticed that since version [4.34.0](https://github.com/wodby/php/releases/tag/4.34.0) locales are not working anymore.
I use this image for a Symfony 5.4 installation with php 8.1 localized in Italian language. Date format now defaults to US notation so  I switched back to [4.33.4](https://github.com/wodby/php/releases/tag/4.33.4) to fix the issue.

Am I missing some settings/configuration?

**Comment by csandanov** [comment]
yes, this is due to alpine upgrade, now we have to install `icu-data-full` package
