### ISSUE TITLE
Compile GD library with AVIF support

### ISSUE THREAD

**Issue by heyyo-droid** [wodby/php#183]
GD supports new format AVIF, but it should be compiled.
It will be great if we could have it inside wodby PHP to benefit from a great compression image library.
https://php.watch/versions/8.1/gd-avif

![image](https://github.com/wodby/php/assets/81759607/2a1dc389-9ac6-448b-9aac-3a6994153558)

**Comment by csandanov** [comment]
Thanks for the suggestion, support added

**Comment by heyyo-droid** [comment]
Thank you :-)
