### ISSUE TITLE
Upgrade xdebug to 3.3.0

### ISSUE THREAD

**Issue by andypost** [wodby/php#185]
ATM there's alpha 3 which is stable enough https://xdebug.org/announcements/2023-10-19

should it wait for RC (if any) or at which stage it possible to upgrade?

PS: flamegraphs out of box are nice

**Comment by csandanov** [comment]
Usually we only update to stable version in main branch because tags could be released automatically, for alpha/beta updates we probably need to create a separate branch with separate beta tags
