### ISSUE TITLE
PHP 8.3 unsupported extensions

### ISSUE THREAD

**Issue by csandanov** [wodby/php#187]
- imagick https://github.com/Imagick/imagick/issues/643
- ~~ds https://github.com/php-ds/ext-ds/issues/199~~
- ~~newrelic https://github.com/newrelic/newrelic-php-agent/issues/676~~

**Comment by andypost** [comment]
Added both to Alpine - ds builds and works fine, imagick too just needs extra dependencies `imagemagick-jpeg` and `imagemagick-svg`

**Comment by csandanov** [comment]
I tried installing this from edge repo and it still fails, `imagick/Imagick.stub.php` needs to be patched  https://github.com/Imagick/imagick/pull/641

```
590.3 Saved /tmp/pear/temp/imagick/ImagickDraw_arginfo.h
590.3 Parse /tmp/pear/temp/imagick/ImagickPixelIterator.stub.php to generate /tmp/pear/temp/imagick/ImagickPixelIterator_arginfo.h
590.4 Saved /tmp/pear/temp/imagick/ImagickPixelIterator_arginfo.h
590.4 Parse /tmp/pear/temp/imagick/ImagickPixel.stub.php to generate /tmp/pear/temp/imagick/ImagickPixel_arginfo.h
590.5 Saved /tmp/pear/temp/imagick/ImagickPixel_arginfo.h
590.5 Parse /tmp/pear/temp/imagick/Imagick.stub.php to generate /tmp/pear/temp/imagick/Imagick_arginfo.h
590.6 In /tmp/pear/temp/imagick/Imagick.stub.php:
590.6 Unterminated preprocessor conditions
590.6 make: *** [Makefile:196: /tmp/pear/temp/imagick/Imagick_arginfo.h] Error 1
590.6 ERROR: `make INSTALL_ROOT="/tmp/pear/temp/pear-build-defaultuserEojndL/install-imagick-3.7.0" install' failed
```

I saw your alpine package though, not sure why it doesn't fail 🤔

**Comment by andypost** [comment]
Yes, the same, I can't get why it builds and pass tests

**Comment by andypost** [comment]
FYI there'shttps://pecl.php.net/package/imagick/3.7.0

**Comment by csandanov** [comment]
3.7 doesn't work, there's a fix in master that needs a release https://github.com/Imagick/imagick/pull/641
