### ISSUE TITLE
XDebug 3.3.0 in 4.41.0 causing CI failures

### ISSUE THREAD

**Issue by wimleers** [wodby/php#188]
👋 Thanks for the awesome work you do with `wodby/php` — it really made my CI setup easy peasy 😊 🙏 

It's been working great for months. Until today.

## CI failures

- Yesterday’s scheduled run: [all green](https://git.drupalcode.org/project/acquia_migrate/-/pipelines/60260)
- Today’s scheduled run: [reproducibly crashing](https://git.drupalcode.org/project/acquia_migrate/-/pipelines/60802) on PHP 8.1 only

Crash:
```
PHP Fatal error:  Uncaught Error: Call to a member function commit() on null in /tmp/test-general-installability/web/core/lib/Drupal/Core/Database/Connection.php:1739
Stack trace:
#0 /tmp/test-general-installability/web/core/lib/Drupal/Core/Database/Connection.php(1725): Drupal\Core\Database\Connection->doCommit()
#1 /tmp/test-general-installability/web/core/lib/Drupal/Core/Database/Connection.php(1678): Drupal\Core\Database\Connection->popCommittableTransactions()
#2 /tmp/test-general-installability/web/core/lib/Drupal/Core/Database/Transaction.php(71): Drupal\Core\Database\Connection->popTransaction()
#3 [internal function]: Drupal\Core\Database\Transaction->__destruct()
#4 {main}
  thrown in /tmp/test-general-installability/web/core/lib/Drupal/Core/Database/Connection.php on line 1739
```

## Analysis
🤔 What could be happening? _Nothing_ has changed overnight. 🤯 

Yesterday:
```
PHP 8.1.26 (cli) (built: Nov 27 2023 23:37:27) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.26, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.26, Copyright (c), by Zend Technologies
    with Xdebug v3.2.2, Copyright (c) 2002-2023, by Derick Rethans
```
Today:

```
PHP 8.1.26 (cli) (built: Dec  1 2023 00:24:07) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.26, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.26, Copyright (c), by Zend Technologies
    with Xdebug v3.3.0, Copyright (c) 2002-2023, by Derick Rethans
```

**Hence this most likely caused by https://github.com/wodby/php/releases/tag/4.41.0 updating XDebug to `3.3.0`.**

**Comment by csandanov** [comment]
Hi, as I understand your main issue is that xdebug was enabled because of `PHP_XDEBUG=0` (the env var should be unset) and despite `PHP_XDEBUG_MODE=off` it still affected your build. 

I recommend using this image with the stability tag, e.g. `wodby/php:8.1-4.40.9`

**Comment by wimleers** [comment]
Ah, but looks like I can't just do `wodby/php:$_TARGET_PHP-dev-4.40.9` because that won't work for PHP 7.4, which I still need to test. Result: [Docker failures](https://git.drupalcode.org/project/acquia_migrate/-/pipelines/60957).

So back to figuring out how to disable XDebug … or perhaps just `XDEBUG_MODE=coverage` is sufficient per https://www.drupal.org/project/drupal/issues/3405976#comment-15348344.

**Comment by csandanov** [comment]
Did you try to unset `PHP_XDEBUG` env var to completely disable xdebug extension? (this is why we introduced this var in addition to the `XDEBUG_MODE`)

Also, I don't know it it's possible in your pipeline, but you can maybe set different image tags for different PHP versions, like the last tag where we still had PHP 7.4 was [4.33.4](https://github.com/wodby/php/releases/tag/) which would be `wodby/php:7.4-dev-4.33.4`

**Comment by wimleers** [comment]
I never set `PHP_XDEBUG`. I'm not sure I _can_ unset it in GitLab CI, as described at https://stackoverflow.com/a/55204041.

**Comment by wimleers** [comment]
… but I did just figure out a way to dynamically set the `-4.40.9` suffix for only some version: https://git.drupalcode.org/project/acquia_migrate/-/merge_requests/14/diffs. 👍
