### ISSUE TITLE
Consider to add php-spx the profiling extension 

### ISSUE THREAD

**Issue by andypost** [wodby/php#189]
It could be disabled by default but no overhead in dev-mode

Ref https://github.com/NoiseByNorthwest/php-spx

**Comment by heyyo-droid** [comment]
I was going to add a new message in this repo to ask for the addition of another opensource profiling PHP extension  https://github.com/wikimedia/mediawiki-php-excimer. 
Longwave recommended on Slack ussing Raven contrib module and Sentry to collect logs, telemetry, and traces .

But now, I see your post it looks like I have another tool to play with :-)

**Comment by andypost** [comment]
I find using flamegraph is the fastest way to figure out bottlenecks,, and bundled UI makes me happy as well
