### ISSUE TITLE
Update sqlite to satisfy Drupal 11

### ISSUE THREAD

**Issue by weitzman** [wodby/php#194]
The Drush builds for Drupal 11 (not yet released) are failing because sqlite is not at 3.45 version. Drupal refuses to install with a lower version. See https://app.circleci.com/pipelines/github/drush-ops/drush/6729/workflows/a22bddb1-a94c-4407-8ed2-4bfef5f119ff/jobs/39552. Any chance we can include a newer sqlite?

Drupal issue - https://www.drupal.org/project/drupal/issues/3346338

**Comment by andypost** [comment]
Alpine 3.20 is coming in next few weeks, which already has sqlite 3.45.3

**Comment by andypost** [comment]
meantime it make sense to build locally until official PHP images will transition to new Alpine
