### ISSUE TITLE
Bash is missing from PATH

### ISSUE THREAD

**Issue by mxr576** [wodby/php#23]
Therefore the following shebang is not working in containers:

```sh
#!/usr/bin/env bash
```
Proposed solution: symlink /bin/bash to /usr/bin/bash.

Image version: wodby/drupal-php:7.1-dev-4.2.2, but I assume the problem relies in this base image.

**Comment by csandanov** [comment]
```
$ docker run --rm -ti wodby/drupal-php:7.1-dev-4.2.2 sh                                                                                             
/var/www/html $ which bash
/bin/bash
/var/www/html $ echo $PATH
/home/wodby/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

We use this shebang in all images and everything works fine

**Comment by mxr576** [comment]
Yes I know, but `#!/usr/bin/env XY` is better, because that way the scripts I wrote for my containers OR wrote for something else but I would like to use them in a container too become possible.
Not all OS-es has `/bin/bash` this is the reason why `#!/usr/bin/env bash` is the preferred shebang that looks for in the PATH to find its location.

**Comment by csandanov** [comment]
I mean we use `#!/usr/bin/env bash` in our scripts and everything works fine. I don't get what is the issue. You write "Bash is missing from PATH" but it's clearly not as I showed you above.

**Comment by mxr576** [comment]
```sh
wodby@php.container:/var/www/html $ /opt/drupal-module/docker-run-tests.sh 
/opt/drupal-module/docker-run-tests.sh: line 1: ﻿#!/usr/bin/env: No such file or directory
    1/29:       https://packages.drupal.org/8/drupal/provider-2013-3$0e85bab1afba4ab56007adf7a883589f21c22c77707493fc8f4f24c4b42415a8.json
```

File: https://github.com/mxr576/apigee-devportal-drupal/blob/8.x-1.x/docker-run-tests.sh

**Comment by csandanov** [comment]
Could you please provide steps to reproduce. Works for me with the latest image:

```shell
$ docker run --rm -ti wodby/drupal-php:7.1 sh                                                                                                       
wodby@php.container:/var/www/html $ printf "#!/usr/bin/env bash\n echo 123;" > test.sh
wodby@php.container:/var/www/html $ chmod +x test.sh
wodby@php.container:/var/www/html $ ./test.sh
123
```
