### ISSUE TITLE
Iconv implementation missing

### ISSUE THREAD

**Issue by alsar** [wodby/php#25]
The iconv extension is enabled, but there is no implementation available (like glibc). I tried with 7.2, 7.1 and 5.6 images.

The php.ini output:  
```
iconv support => enabled
iconv implementation => unknown
iconv library version => unknown
iconv.input_encoding => no value => no value
iconv.internal_encoding => no value => no value
iconv.output_encoding => no value => no value
```
As a result the iconv() function fails with translit:
`iconv('utf-8', 'ascii//TRANSLIT', 'test');` 

`Notice: iconv(): Wrong charset, conversion from 'utf-8' to 'ascii//TRANSLIT' is not allowed`

**Comment by csandanov** [comment]
Thanks for reporting this, the lib was really missing. The implementation and the version will still be missing despite the fix but you can validate that it's working now by running the following snippet in the container as suggested in https://github.com/docker-library/php/issues/240#issuecomment-306246179
```bash
php -d error_reporting=22527 -d display_errors=1 -r 'var_dump(iconv("UTF-8", "UTF-8//IGNORE", "This is the Euro symbol '\''€'\''."));'
```
If it runs without notices it's all good.

**Comment by alsar** [comment]
It works now. Thank you for the quick resolution.

**Comment by alsar** [comment]
@csandanov The fix works with the CLI but not with FPM.

CLI environment variables:
```
LD_PRELOAD => /usr/lib/preloadable_libiconv.so php
$_SERVER['LD_PRELOAD'] => /usr/lib/preloadable_libiconv.so php
$_ENV['LD_PRELOAD'] => /usr/lib/preloadable_libiconv.so php
```

But those variables are missing with FPM.

**Comment by csandanov** [comment]
Yes, that's because FPM has `clear_env = yes` by default. Added `LD_PRELOAD` to the list of env vars that always pass through.

**Comment by alsar** [comment]
I tried the updated image. The environment variables are now present, but the iconv function with translit still fails with FPM.

**Comment by csandanov** [comment]
Does it work if you set `clear_env = yes` and `LD_PRELOAD=/usr/lib/preloadable_libiconv.so php-fpm`?

**Comment by alsar** [comment]
No. I changed this line https://github.com/wodby/php/blob/master/7/Dockerfile#L52 from `php` to `php-fpm`. Is this correct?

The container was built, but it still works only for he CLI but not FPM.

**Comment by csandanov** [comment]
Right, we run fpm via sudo. Added `LD_PRELOAD` directly to the command, my example from above now runs without notices via fpm as well.

**Comment by alsar** [comment]
It works now. Thanks.

Just a remark. On my local setup he command `php -r "var_dump(iconv('UTF-8', 'ASCII//TRANSLIT', 'tést'));"` outputs `test`, but with your image it's `t'est`. 
Do you know maybe what is this related to? Locales maybe?

**Comment by csandanov** [comment]
What's your OS? AFAIK, Linux and Windows use different libs for iconv

**Comment by csandanov** [comment]
Could be https://github.com/docker-library/php/issues/240#issuecomment-381077806

**Comment by alsar** [comment]
Probably.

When I output `setlocale(LC_ALL, 0);` I get:
localy: `LC_CTYPE=en_US.UTF-8;LC_NUMERIC=C;LC_TIME=C;LC_COLLATE=C;LC_MONETARY=C;LC_MESSAGES=C;LC_PAPER=C;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=C;LC_IDENTIFICATION=C`

container: `C.UTF-8;C;C;C;C;C`

**Comment by csandanov** [comment]
I doubt this issue can be resolved, most likely this caused due to usage of GNU iconv library and [not having a good locale support](https://github.com/gliderlabs/docker-alpine/issues/144) in musl, try using http://php.net/manual/en/transliterator.transliterate.php instead for transliteration:
```
php -r 'var_dump(transliterator_transliterate("Any-Latin; Latin-ASCII; [\u0080-\u7fff] remove", "A æ Übérmensch på høyeste nivå! И я люблю PHP! есть. ﬁ ¦"));'
```

**Comment by gsusI** [comment]
Fixed by installing `php7-mbstring` `php7-iconv` in that order

```bash
RUN apk --no-cache add php7-mbstring php7-iconv
```

**Comment by csandanov** [comment]
Fixed in the upstream https://github.com/docker-library/php/pull/1264
