### ISSUE TITLE
How to run the CROND mode?

### ISSUE THREAD

**Issue by aledelgo** [wodby/php#26]
I've added the CRONTAB env var in my docker-compose file but nothing happens (/etc/crontabs/www-data
 file is empty ).

i tried to clone the php service with the crontab env var and set 
```
command: 
     - "sudo"
     - "-E"
     - "crond"
```
to pass this cmd arguments to the entrypoint script because i can read this:
https://github.com/wodby/php/blob/8b14714c4e94f928c2dcfa3b89052a706366aaf1/7/docker-entrypoint.sh#L91

but in this case the service start and stop immediately without errors.

any hint?

**Comment by csandanov** [comment]
See how we run crond in tests: https://github.com/wodby/php/blob/master/7/test/docker-compose.yml#L81
