### ISSUE TITLE
Composer cache

### ISSUE THREAD

**Issue by divined** [wodby/php#28]
Cannot create cache directory /.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache

Composer without cache very slow!

**Comment by csandanov** [comment]
Are you trying to create a `/.compose`? Why not in home directory?

```bash
$ docker run --rm -ti wodby/php:7.1 sh                                                                                              [13:05:45]
$ id
uid=1000(wodby) gid=1000(wodby) groups=82(www-data),1000(wodby)
$ ls -la ~/.composer/
total 24
drwxr-sr-x    3 wodby    wodby         4096 May 22 06:27 .
drwxr-sr-x    5 wodby    wodby         4096 Jun  4 06:05 ..
-rw-r--r--    1 wodby    wodby           13 May 22 06:27 .htaccess
-rw-r--r--    1 wodby    wodby           63 May 22 06:27 composer.json
-rw-r--r--    1 wodby    wodby         2283 May 22 06:27 composer.lock
drwxr-sr-x    4 wodby    wodby         4096 May 22 06:27 vendor
```

**Comment by divined** [comment]
I have ~/.composer directory
But composer can't get access to it.  I use drupal-php with docker-compose.

**Comment by divined** [comment]
docker-compose exec php composer require {something} will return the error:
Cannot create cache directory /.composer/cache/repo/https---packagist.org/, or directory is not writable.

**Comment by divined** [comment]
sorry, i use 
alias composer="docker-compose exec --user 1000 php composer"

I use 1000 uid, becquse i need all files generated by composer must be available for my host user.

But the question is how to mix this?

**Comment by csandanov** [comment]
What is your image tag? Please provide steps to reproduce it. See my previous comment, all permissions are correct and the default user already has uid 1000 in the latest image.

**Comment by divined** [comment]
Yes, lastest build is perfect, thx a lot man and good job )
