### ISSUE TITLE
Drop mcrypt for PHP 7.1

### ISSUE THREAD

**Issue by rodrigoaguilera** [wodby/php#3]
Since mcrypt in PHP 7.1 Raises exceptions
https://wiki.php.net/rfc/mcrypt-viking-funeral

I think the wisest thing is to remove.

What software dependending on this image requires mcrypt?

**Comment by csandanov** [comment]
Do you

**Comment by csandanov** [comment]
> In PHP 7.1, all mcrypt_* functions will raise an E_DEPRECATED notice.

I think it's OK, you won't see any notices unless you use these functions. What exceptions do you get?

**Comment by rodrigoaguilera** [comment]
No extra exceptions but from calling the functions but I feel is more neat not to keep nor maintain deprecated code. But I just wanted the opinion so is OK.

**Comment by csandanov** [comment]
mcrypt preserved for 7.2 (installed from pecl) because a lot of frameworks still use it
