### ISSUE TITLE
Idea: default configuration script for xdebug.remote_host

### ISSUE THREAD

**Issue by mxr576** [wodby/php#30]
If PHP_XDEBUG_REMOTE_HOST env. variable is not set then[ a similar script](https://github.com/amazeeio/lagoon/blob/fa5281f463ac213c0076c1117dac1110665434fa/images/php/fpm/entrypoints/60-php-xdebug.sh#L4) could try to set the default value if PHP_XDEBUG_DEFAULT_ENABLE is set to 1.

**Comment by csandanov** [comment]
this might be a useful tool for a local dev image but since this image also used in production we're not going to add, it's super weird to me when some auto script does something to your configuration without you knowing
