### ISSUE TITLE
Environment Variables are ignored.

### ISSUE THREAD

**Issue by brandonkal** [wodby/php#31]
env variables set in `.env` are ignored.
```
PHP_TAG=7.2-dev-4.4.4

PHP_UPLOAD_MAX_FILESIZE=64M
PHP_POST_MAX_SIZE=64M
PHP_MAX_EXECUTION_TIME=300
```

This isn't being set properly.

**Comment by csandanov** [comment]
From https://docs.docker.com/compose/env-file/:

> Environment variables defined in the .env file are not automatically visible inside containers. To set container-applicable environment variables, follow the guidelines in the topic Environment variables in Compose, which describes how to pass shell environment variables through to containers, define environment variables in Compose files, and more.
