### ISSUE TITLE
Why is there SSHd in this container?

### ISSUE THREAD

**Issue by brandonkal** [wodby/php#32]
When I docker exec into the php container, I see that that sshd exists inside the container. That seems to be against best practices. If ssh was needed, it should be handled by the host or as a seperate container for the process.

**Comment by csandanov** [comment]
Not sure what you mean. We don't run fpm and sshd in the same container, you run different containers but with the same image to have a consistent environment

**Comment by brandonkal** [comment]
To reproduce what I am seeing:

```
$ docker run --name php -d wodby/php
$ docker exec php bash -c 'which sshd'
/usr/sbin/sshd
```
There I can see the sshd binary exists in the container. If I bash into the container and explore, I also find that sshd config files also exist within the php container. I see you have a wodby/sshd container which seems to be completely different from this one.

**Comment by csandanov** [comment]
normally, when you ssh you expect to have the same environment – php version, composer, drush, etc. That's why you need exactly the same image
