### ISSUE TITLE
Add graphicsmagick

### ISSUE THREAD

**Issue by LexBritvin** [wodby/php#33]
Please, add graphicsmagick. It is better optimized. In some cases, Imagemagick takes all resources when using Image styles in Drupal. GM handles it ok.

**Comment by csandanov** [comment]
[Pecl extension](http://pecl.php.net/package/gmagick) still has no stable version and received 1 update in the last 2 years. I don't think it's worth including to the list of generic extensions at this point.

**Comment by sameronline** [comment]
@csandanov what is the best way if i want to include GraphicsMagick extension through DockerFile?

**Comment by csandanov** [comment]
install pecl extension and the lib as done for other extensions

**Comment by csandanov** [comment]
Closed until the stable version of [gmagick](http://pecl.php.net/package/gmagick) will be released
