### ISSUE TITLE
Adding PHP extension : php_rdkafka

### ISSUE THREAD

**Issue by sailorphoenix** [wodby/php#34]
Hello!

I publish an issue to know if it possibles to add php-rdkafka extension to drupal-php image? I tried on my own without success. If we can add this on the main image, I will be very grateful.

PHP Version : 7.1
ext-rdkafka wanted : 3.0 at least

Thanks a lot!

**Comment by sailorphoenix** [comment]
Thanks so much for your commit!
Which tag can we use to deploy these changes with docker4drupal?

**Comment by sailorphoenix** [comment]
@csandanov , how can we create a new tag to produce a docker image?
I wish to test it with my projet (I have a corporate proxy that blocked apk and pear :'( )
Thanks a lot for your job!

**Comment by csandanov** [comment]
Released `-4.5.1` with rdkafka

**Comment by sailorphoenix** [comment]
Oh great!!! Thank you so much :D
