### ISSUE TITLE
No access to environment variables outside of dev images

### ISSUE THREAD

**Issue by bvalerius** [wodby/php#35]
Running `5.6-dev` gives me access to the environment vars I'm passing in through docker-compose, running non-dev image does not. Is this intended? How can I access them on the production ready images?

**Comment by csandanov** [comment]
You can set `PHP_FPM_CLEAR_ENV=no`, by default it's `yes` for security reasons. Alternatively you can specify a list of accessible env vars via `PHP_FPM_ENV_VARS` (json array).
