### ISSUE TITLE
Add option phar.readonly to php.ini

### ISSUE THREAD

**Issue by jurgenhaas** [wodby/php#39]
Could you please add this option to the various php.ini files:

```
phar.readonly = {{ getenv "PHP_PHAR_READONLY" "1" }}
```

We could then change that to 0 (zero) when we have an application that needs to write to a phar file.

**Comment by csandanov** [comment]
Added, available since -4.5.0

**Comment by jurgenhaas** [comment]
Thanks for the quick turnaround, works great.
