### ISSUE TITLE
Any plans to maintain a Debian based branch?

### ISSUE THREAD

**Issue by lukasz-zaroda** [wodby/php#4]
Unfortunately ionCube Loader don't work on Alpine Linux ( https://serverfault.com/questions/802228/does-the-ioncube-have-problems-with-php-running-on-musl-libc , http://forum.alpinelinux.org/forum/general-discussion/strange-behavior-different-ubuntu), and this is a very popular extension. I think it would be a good idea to maintain a Debian branch of PHP images just for this reason. I know it's not fun, but it would be very useful.

**Comment by csandanov** [comment]
Hi, we stick to Alpine only at the moment. The trend is obvious – Alpine is a standard for docker images. You should probably submit a request to ionCube guys so they support Alpine, everyone uses it nowadays.
