### ISSUE TITLE
How to add `ext-uuid`?

### ISSUE THREAD

**Issue by liverbool** [wodby/php#43]
Hi, How i can add/install `ext-uuid`?

eg. `pecl install uuid`

Thanks.

**Comment by csandanov** [comment]
You'll have to build your own image (fork this repo or build on top), see Dockerfile to learn how we install other pecl extensions. 

Is there a reason you need the pecl extension for uuid instead of using a composer project like https://github.com/ramsey/uuid?

**Comment by csandanov** [comment]
Added in [4.7.2](https://github.com/wodby/php/releases/tag/4.7.2)
