### ISSUE TITLE
docker run --user presents sudo prompt

### ISSUE THREAD

**Issue by andriokha** [wodby/php#50]
Hi, thanks for all the work on maintaining the wodby images!

I'm using them to locally serve a Drupal website which is built via composer. Ideally I'd be using the same service to do the building as to do the serving (or at least an identically configured PHP). I've had no problem using `docker-compose exec --user www-data php composer` when the service is already running, but if I use `docker-compose run --user www-data php composer` I'm given the `sudo` prompt for `www-data`:
```
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.
```
I can reproduce more simply with `docker run -it --user www-data wodby/php:7.2 whoami`. I'm assuming it's connected to the `sudo`s in `docker-entrypoint.sh`.

It's low impact because there's a workaround, but at least for me it was quite confusing! (I'm not a Docker expert tho...) I was wondering if there was some way to make it work, or maybe if it was worth adding something to the readme?

Thanks again!

**Comment by csandanov** [comment]
You should not use `www-data` user for your codebase, it should be owned by `wodby` user https://github.com/wodby/php#users-and-permissions
