### ISSUE TITLE
Add support for Phalcon

### ISSUE THREAD

**Issue by msajko** [wodby/php#52]
I believe we can as well add support for [Phalcon](https://phalconphp.com) as php extension

In the meantime here is Dockerfile solution:
```
ARG PHP_TAG_ROW

FROM wodby/php:${PHP_TAG_ROW}
USER root
RUN mkdir -p /usr/src/php/ext && \
    curl -L -o /usr/src/php/ext/phalcon.tar.gz https://github.com/phalcon/cphalcon/archive/v3.3.1.tar.gz && \
    tar xzf /usr/src/php/ext/phalcon.tar.gz -C /usr/src/php/ext && \
    rm /usr/src/php/ext/phalcon.tar.gz && \
    mv /usr/src/php/ext/cphalcon-3.3.1 /usr/src/php/ext/phalcon

RUN docker-php-ext-install -j$(nproc) /usr/src/php/ext/phalcon/build/php7/64bits
```

**Comment by csandanov** [comment]
What is the size of the compiled cphalcon extension?

**Comment by msajko** [comment]
- wodby/php 7.2-dev-4.8.2
  * def. **348** MB
  * with Phalcon (Dockerfile) **532** MB
    * cphalcon-3.3.1 in  /usr/src/php/ext/phalcon/ 57.3 M

**Comment by csandanov** [comment]
Ok, it's pretty big, we can't add it to the base image. If we're going to add it will be added as a separate image based on wodby/php.
