### ISSUE TITLE
Add Xdebug for PHP 7.3

### ISSUE THREAD

**Issue by csandanov** [wodby/php#56]
https://bugs.xdebug.org/view.php?id=1519

**Comment by ecotechie** [comment]
Could this be added to the readme.md? I literally spent over three hours trying to get Xdebug to connect, only to find out 7.3 wouldn't work. Downgraded to 7.2 and easy as pie.

My fault, I know, but it may save some people a lot of grief. 

Also, thanks for all your awesome work. Getting a lot out of this and the WordPress repos!

**Comment by ecotechie** [comment]
Great, so not only am I dense, I also can't RTFD? Thanks and sorry to waste your time.

**Comment by csandanov** [comment]
Xdebug was updated to 2.7.0 and now works with PHP 7.3 since [4.11.3](https://github.com/wodby/php/releases/tag/4.11.3)
