### ISSUE TITLE
Adding bin directory to the PATH

### ISSUE THREAD

**Issue by alsar** [wodby/php#60]
Applications commonly symlink composer binaries to the `bin` directory instead of the standard `vendor/bin`directory.
Could the `bin` directory also be added to the path inside the [Dockerfile](https://github.com/wodby/php/blob/4.9.0/7/Dockerfile#L21)?

**Comment by csandanov** [comment]
Do you mean `/var/www/html/bin` or `/bin`?

**Comment by alsar** [comment]
`/var/www/html/bin`

**Comment by csandanov** [comment]
Added
