### ISSUE TITLE
Issue with APP_ROOT, and adding different directories to PATH

### ISSUE THREAD

**Issue by marcinmaruszewski** [wodby/php#62]
I saw that in https://github.com/wodby/php/issues/60 you added `/var/www/html/bin` directory to `$PATH`. That's great. But what if my application root directory is inside `/var/www/html/web` and composer binaries are inside `/var/www/html/web/bin` or `/var/www/html/web/vendor/bin`.

I tried to change $APP_ROOT to `/var/www/html/web` but when I check the value of $PATH it's acting like $APP_ROOT is still `/var/www/html`.

So I think there are things to do:
1. We should allow the user to set $ADD_PATH variable inside docker-compose.yml file and add it to $PATH. It would be easier to do it than adding different directories inside this PHP image.
2. I think there is an issue with $APP_ROOT. I changed it to `/var/www/html/web` but when I enter container using make ssh (from docker4php stack) workdir is `/var/www/html`, and it's wrong.

I'm using PHP image 7.3-dev-4.10.0

**Comment by csandanov** [comment]
`$APP_ROOT` is currently not intended to be customized because it's used during the image build. 

> But what if my application root directory is inside /var/www/html/web and composer binaries are inside /var/www/html/web/bin or /var/www/html/web/vendor/bin.

Normally you should have `vendor` dir in the app root and `web` is the directory that used as HTTP docroot, see https://github.com/wodby/drupal-composer for example

**Comment by marcinmaruszewski** [comment]
@csandanov, thanks for the update. I understand that in case of using Drupal this is desirable behavior. But in this case, I'm using docker4php stack with Grav application. As you can see in the source (https://github.com/getgrav/grav) there is a bin directory inside docroot. 

To be honest, right now I realized that I can do it in a different way. I can change volumes mapping so I'll point my host `./web` directory to `/var/www/html` and set HTTP server docroot to `/var/www/html`. I think this will solve my issue because thanks to #60 `/var/www/html/bin` directory is already in `$PATH`. 

Thanks for helping me with this!

**Comment by csandanov** [comment]
Also, you can add/commit a symlink from your docroot to the repo root
