### ISSUE TITLE
[NewRelic] Add support of "browser_monitoring.auto_instrument" config

### ISSUE THREAD

**Issue by PavelPrischepa** [wodby/php#66]
We have to make [browser_monitoring.auto_instrument](https://docs.newrelic.com/docs/agents/php-agent/configuration/php-agent-configuration#inivar-autorum) option configurable via an environment variable. To make an ability to disable automatic injection of the New Relic Browser snippet on particular pages.

**Comment by csandanov** [comment]
Added in 4.11.0
