### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by szeidler** [wodby/php#68]
Have you considered to build GD with WebP support? We're currently playing around with image optimization methods and want to give it a try, as more browsers are going to support this file format now.

Currently the function `imagewebp` is not available.

**Comment by csandanov** [comment]
I've added webp support to gd to the `latest` image, could you please try it out.

**Comment by szeidler** [comment]
Thanks @csandanov. It works perfect locally!

**Comment by csandanov** [comment]
Added to [4.11.1](https://github.com/wodby/php/releases/tag/4.11.1)
