### ISSUE TITLE
Add env var to choose PHP FPM process manager

### ISSUE THREAD

**Issue by rubach** [wodby/php#7]
I'm proposing adding an environment variable that lets you choose the process manager used by PHP FPM. It is set to dynamic in the zz-www.conf.tpl file. It would be nice to have an environment variable that defaults to dynamic, but lets you change it to ondemand or static if wanted.

[This article](https://ma.ttias.be/a-better-way-to-run-php-fpm/) I found states that ondemand can be better in some situations. I noticed a significant memory consumption decrease when I switched to ondemand. 

If this added, another environment variable should be included that lets the user set pm.process_idle_timeout.

**Comment by csandanov** [comment]
The support has been added
