### ISSUE TITLE
Adding support of PDO Oracle 

### ISSUE THREAD

**Issue by julfabre** [wodby/php#72]
Hi !

I publish an issue to know if it possibles to add pdo oci  extension to drupal-php image? I tried on my own without success. If we can add this on the main image, I will be very grateful.

PHP Version : 7.x 
OCI : 11 or 12

Thanks a lot !

**Comment by csandanov** [comment]
AFAIK it's not compatible with musl libc and we won't install glibc just for this extension, there are dirty workarounds though outlined at https://stackoverflow.com/questions/38206964/compile-php-oci8-extension-under-alpinelinux
