### ISSUE TITLE
Allow change xdebug version with build args

### ISSUE THREAD

**Issue by mistermoper** [wodby/php#78]
Hello. In some cases the xdebug version which is installed (2.7.2 right now) it doesn't work in specific IDES (phpstorm 2018.1). With the same php container and upgrading to phpstorm 2019 is working correctly.

This problem is solved downgrading phpstorm version to 2.6.1.

So what if we let override the xdebug version in Dockerfile with and ARG?

**Comment by csandanov** [comment]
Replied in PR
