### ISSUE TITLE
Question: Why is /usr/src/php.tar.xz removed?

### ISSUE THREAD

**Issue by kevin-coyle** [wodby/php#8]
We were trying to install the mbstring extension to this image (this is for a drupal project). However we're unable to install any extensions because those directories have been removed.

How come this directory has been removed? Also, do you have a solution for adding extensions easier rather than having to copy this docker file and then have drupal one extend that?

Thanks for the work so far :)

**Comment by csandanov** [comment]
mbstring extension already installed in these images

**Comment by kevin-coyle** [comment]
is it? I can't seem to see it in the dockerfile and it's not reporting that it's installed. I'll double check to be sure.

**Comment by csandanov** [comment]
Run `php -m`

**Comment by kevin-coyle** [comment]
I can see it on my copy but I'll double check with my colleague who was having the issue with mbstring.
Still though, how come the sources are removed? is this just to slim down the image?

**Comment by csandanov** [comment]
Yes, it is.
