### ISSUE TITLE
Add extentsion opencensus to support opentracing api jaeger / zipkin /etc.

### ISSUE THREAD

**Issue by virtuman** [wodby/php#81]
Install php extension that allows to easily instrument php applications. See PR #80 for more details. 
Having extensions installed shouldn't create any performance hit, although - creators of application and the opentracing api community claim that this type of tracing is absolutely safe to run in production. We have it running on high-traffic production site for quite some time now, and see no effect on resource utilization across our farms.

Thank you for consideration.

**Comment by virtuman** [comment]
would you consider re-visiting related PR because even GOOGLE considers this package to be stable enough to have it included in their docs:

https://cloud.google.com/trace/docs/setup/php

**Comment by csandanov** [comment]
opentelemetry extension has been added
