### ISSUE TITLE
Why is prestissimo not included in the dockerfile?

### ISSUE THREAD

**Issue by jbertoen** [wodby/php#82]
Documentation mentions the prestissimo composer library. But it is not included anymore since https://github.com/wodby/php/commit/ef87ee87271c041522b71df48b7462dc06bbd853

Why is that?

**Comment by csandanov** [comment]
this package caused composer install failures https://github.com/wodby/docker4drupal/issues/365

here's explained why: https://github.com/drupal-composer/drupal-scaffold/issues/101#issuecomment-488758925

**Comment by SyneticDevOps** [comment]
Why not make it optional with an env variable setting and require it through an init.sh script in the entrypoint setup?
Tried that and seems to work. Do not get any issues for now...
