### ISSUE TITLE
[NewRelic] Add support for debugging

### ISSUE THREAD

**Issue by mralexho** [wodby/php#85]
After noticing our agent stopped receiving browser metrics, I contacted NewRelic and the technical support engineer asked me to set the following configs:

```
newrelic.loglevel = "verbosedebug"
newrelic.daemon.loglevel = "verbosedebug"
newrelic.special=debug_autorum
```

Since I can't edit these values, NewRelic is unable to help debug the issue. Can you please enable these? Thanks.

**Comment by csandanov** [comment]
We already have an env var for `newrelic.loglevel` which I guess normally should be enough to figure out the issues, I guess adding `newrelic.daemon.loglevel` won't be a big problem (PR is welcomed). And I couldn't find anything about `newrelic.special` at https://docs.newrelic.com/docs/agents/php-agent/configuration/php-agent-configuration does this option even exists?

**Comment by mralexho** [comment]
Thanks @csandanov, here's the latest response from NewRelic:


Hi Alex,

I'm checking in to see if you have any news? I took a look at the issue tracker on github and noticed that there was a question about the 
`newrelic.special config`. This isn't a publicly documented configuration option because it's only use is for us to troubleshoot our agents. I would like to highlight that this configuration option is a requisite step in troubleshooting this issue.

Please let me know where you're at in this process. I look forward to your reply.

Ben Abbott
Technical Support Engineer
New Relic

**Comment by mralexho** [comment]
Is there anyway to add this param?

**Comment by csandanov** [comment]
Added in https://github.com/wodby/php/releases/tag/4.12.4

**Comment by mralexho** [comment]
Thanks @csandanov 👍
