### ISSUE TITLE
Is it possible to change Alpine Version?

### ISSUE THREAD

**Issue by albertski** [wodby/php#93]
Is it possible to set the Alpine version to 3.8? I just upgraded to php 7.2  (`7.2-dev-4.13.11`) and I'm assuming it is using Alpine 3.9 but I need to add the `pdftk` library which won't work with Alpine 3.9.

**Comment by csandanov** [comment]
You can change a basic image from `wodby/base-php` to a necessary tag from https://hub.docker.com/_/php and rebuild the image.

**Comment by albertski** [comment]
Thanks.
